version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: enterpriseauth-postgres

    environment:
      POSTGRES_DB: enterpriseauthdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .

    container_name: enterpriseauth-app

    depends_on:
      - postgres

    ports:
      - "8085:8085"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/enterpriseauthdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  postgres_data: