spring:
  application:
    name: enterprise-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/enterprise_auth_db
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8085

jwt:
  secret: mySuperSecretKeyForEnterpriseAuthStarter123456
  expiration: 900000